### PR TITLE
Save and retrieve data in hdf5

### PR DESCRIPTION
**Pull request by usmanwardag**
Adds options to save and retrieve data in hdf5. Not yet ready to merge.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Thanks !

**Comment by usmanwardag** [comment]
Oops, forgot to mention but it wasn't ready for merging.

**Comment by OrkoHunter** [comment]
Oh, If only the travis build is the problem, then I can commit about that.

**Comment by usmanwardag** [comment]
Nope, need to add some other stuff too. You can keep this closed, I will create a new PR when other commits are ready.

**Comment by OrkoHunter** [comment]
Oh okay ! Sorry for the trouble.

**Comment by usmanwardag** [comment]
No issues.

**Pull request merged**
