### PR TITLE
Changes to matrix and time and frequency attributes

### PR DESCRIPTION
**Pull request by evandromr**
I made the changes suggested by @dhuppenkothen in this comment: https://github.com/StingraySoftware/stingray/pull/132#issuecomment-244134027

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@evandromr Hey! I think you need to create a PR on [StingraySoftware/Stingray](https://github.com/StingraySoftware/Stingray).
This repository is merely a fork of the main repository.

**Comment by evandromr** [comment]
But there's already a PR on Stingray, from this fork/branch. :thinking: 
Should I open a new Dynamical Powerspectrum PR there? Does that mean you are going to close your PR?

**Comment by OrkoHunter** [comment]
Oh @evandromr, I'm sorry, I thought you sent this on my master.

Can you please cherry-pick my commits and then add your commits to create a new PR? I shall close the PR from this branch.

**Comment by evandromr** [comment]
Done. I'm closing this one.

**Pull request closed without merging**
